blank_issues_enabled: false
contact_links:
  - name: â“ Question
    url: https://matrix.to/#/#mollyim:matrix.org
    about: Please ask and answer questions in our chat room.
  - name: ğŸ“š Translation Feedback
    url: https://hosted.weblate.org/projects/molly-instant-messenger/
    about: Share feedback on translations.